# Generated by Django 3.2.18 on 2023-11-09 19:53

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=events.models.Event.get_path, verbose_name='Баннер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('age_limit', models.IntegerField(blank=True, default=0, verbose_name='Возрастное орграничение')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена')),
                ('total_tickets', models.IntegerField(blank=True, default=0, verbose_name='Количество билетов')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('artist', models.CharField(blank=True, max_length=256, null=True, verbose_name='Артист')),
                ('pushkin_payment', models.BooleanField(default=False, verbose_name='Оплата по пушкинской')),
                ('want_pushkin', models.IntegerField(blank=True, default=0, verbose_name='Хочу по пушкинской')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.EventImage.get_path, verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Файл события',
                'verbose_name_plural': 'Файлы события',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Площадка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адресс')),
                ('location_data', models.JSONField(blank=True, null=True, verbose_name='2GIS данные')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('events', models.ManyToManyField(blank=True, related_name='eventtopics_event', to='events.Event', verbose_name='События')),
            ],
            options={
                'verbose_name': 'Подборка событий',
                'verbose_name_plural': 'Подборки событий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='events_image', to='events.EventImage', verbose_name='Фотографии мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.platform', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events_tag', to='events.Tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='events.Tag', verbose_name='Тэги'),
        ),
    ]
