# Generated by Django 3.2.18 on 2023-11-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customroute',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель маршрута'),
        ),
        migrations.AddField(
            model_name='customroute',
            name='waypoints',
            field=models.ManyToManyField(blank=True, related_name='customroutes_event', to='events.Event', verbose_name='Точки маршрута'),
        ),
    ]
