# Generated by Django 3.2.18 on 2023-11-10 15:44

import attractions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=attractions.models.Attraction.get_path, verbose_name='Баннер')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('musculoskeletal_disorders', models.BooleanField(blank=True, null=True, verbose_name='Нарушения опорно-двигательного аппарата')),
                ('visual_impairment', models.BooleanField(blank=True, null=True, verbose_name='Нарушения зрения')),
                ('hearing_impairment', models.BooleanField(blank=True, null=True, verbose_name='Нарушения слуха')),
                ('intellectual_impairment', models.BooleanField(blank=True, null=True, verbose_name='Нарушения интеллекта')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
            },
        ),
    ]
