# Generated by Django 3.2.18 on 2023-11-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
