# Generated by Django 3.2.18 on 2023-11-10 20:51

import attractions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_alter_attraction_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=attractions.models.Attraction.get_path, verbose_name='Баннер'),
        ),
    ]
