# Generated by Django 3.2.18 on 2023-11-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_auto_20231111_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='lot',
        ),
        migrations.AddField(
            model_name='attraction',
            name='lon',
            field=models.CharField(default=1.4, max_length=255, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attraction',
            name='lat',
            field=models.CharField(max_length=255, verbose_name='Широта'),
        ),
    ]
